name: Déploiement Documentation (GitHub Pages)

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Déployer sur GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Pages
        uses: actions/configure-pages@v5

      - name: Upload de l'artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
